#!/usr/bin/env python

import rospy
from nav_msgs.msg import Odometry
from nav_msgs.msg import OccupancyGrid
from sensor_msgs.msg import LaserScan
from tf.transformations import euler_from_quaternion
import tf2_ros as tf
from geometry_msgs.msg import Twist
from std_msgs.msg import String
import math
import cmath
import numpy as np
import time
from visualization_msgs.msg import Marker
from nav_class import Navigation

import cv2
from cv_bridge import CvBridge, CvBridgeError

laser_range = np.array([])
occdata = []

yaw = 0.0
rotate_speed = 0.1
linear_speed = 0.1
stop_distance = 0.25

occ_bins = [-1, 0, 100, 101]
front_angle = 30
front_angles = range(-front_angle, front_angle+1, 1)

occ_grid = []
bot_pos = ()
checked_positions = []
map_height = 0
map_width = 0

target_in_sight = False
horizontal_amount = 0
vertical_amount = 0

cam_angle = 30

navigator = Navigation(linear_speed, rotate_speed)

def odom_cb(msg):
	global yaw

	orientation_quat = msg.pose.pose.orientation
	orientation_list = [orientation_quat.x, orientation_quat.y, orientation_quat.z, orientation_quat.w]
	(roll, pitch, yaw) = euler_from_quaternion(orientation_list)
	# rospy.loginfo('[YAW]: %f', yaw)
	navigator.update_yaw(yaw)

def laser_scan_cb(msg):
	global laser_range
	laser_range = np.array([msg.ranges])
	navigator.update_laserscan_data(laser_range)

def occ_cb(msg, tf_buf):
	global occdata
	global bot_pos
	global occ_grid

	occdata = np.array([msg.data])
	occ_counts = np.histogram(occdata, occ_bins)
	total_bins = msg.info.width * msg.info.height

	# rospy.loginfo('Unmapped: %i, Unoccupied: %i, Occupied: %i, Total: %i', occ_counts[0][0], occ_counts[0][1], occ_counts[0][2], total_bins)

	trans2 = tf_buf.lookup_transform('map', 'base_link', rospy.Time(0))
	cur_pos = trans2.transform.translation
	map_res = msg.info.resolution
	map_origin = msg.info.origin.position
	grid_x = int((cur_pos.x - map_origin.x)/map_res)
	grid_y = int((cur_pos.y - map_origin.y)/map_res)
	bot_pos = (grid_x, grid_y)
	rospy.logdebug('[NAV] current position: %s', str(bot_pos))

	oc2 = occdata + 1
	occ_grid = np.uint8(oc2.reshape(msg.info.height, msg.info.width, order='F'))

	# navigator.update_bot_pos((bot_pos[1],bot_pos[0]))
	navigator.update_bot_pos(bot_pos)
	navigator.update_occ_grid(occ_grid, map_origin, map_res)

def target_identified_cb(msg):
	global target_in_sight
	if msg.data:
		target_in_sight = True
		navigator.update_target_pos()
	else:
		target_in_sight = False

def target_horizontal_cb(msg):
	global horizontal_amount
	horizontal_amount = msg.data

def target_vertical_cb(msg):
	global vertical_amount
	vertical_amount = msg.data

def stopbot():
    # publish to cmd_vel to move TurtleBot
    pub = rospy.Publisher('cmd_vel', Twist, queue_size=10)

    twist = Twist()
    twist.linear.x = 0.0
    twist.angular.z = 0.0
    time.sleep(1)
    pub.publish(twist)

def mapper():
	rospy.init_node('mapper', anonymous=True)

	tf_buf = tf.Buffer()
	tf_listener = tf.TransformListener(tf_buf)
	rospy.sleep(1.0)

	rospy.Subscriber('odom', Odometry, odom_cb)
	rospy.Subscriber('scan', LaserScan, laser_scan_cb)
	rospy.Subscriber('map', OccupancyGrid, occ_cb, tf_buf)

	rospy.Subscriber('/target/identified', Bool, target_identified_cb)
	rospy.Subscriber('/target/horizontal', Int8, target_horizontal_cb)
	rospy.Subscriber('/target/vertical', Int8, target_vertical_cb)

	pub_aim = rospy.Publisher('/servo/aiming', Int8, queue_size=10)
	pub_fire = rospy.Publisher('/servo/firing', Bool, queue_size=10)

	rospy.on_shutdown(stopbot)
	rospy.sleep(3)

	start_time = time.time()

	# navigator.test_funct('')

	ret_map = navigator.map_region()

	with open('maptime.txt', 'w+') as f:
		f.write("Elapsed time: " + str(time.time() - start_time))

	cv2.imwrite('maze_map.png', ret_map)
	cv2.imwrite('maze_map2.png', navigator.occ_map_raw)

	# navigator.return_to_home()
	if navigator.clr_target_located:
		# navigator.move_to_clr_trgt()
		rate = rospy.Rate(5)
		while not target_in_sight and abs(horizontal_amount) > 10:
			if not target_in_sight:
				navigator.move_bot(0.0,rotate_speed)
			if horizontal_amount > 10:
				navigator.move_bot(0.0,-1*rotate_speed)
			elif horizontal_amount < 10:
				navigator.move_bot(0.0, rotate_speed)

			rate.sleep()

		pub_aim.publish(cam_angle + (21.2*vertical_amount))
		time.sleep(3)
		pub_fire.publish(True)

	# rospy.spin()
	exit()

if __name__ == '__main__':
	try:
		mapper()
	except rospy.ROSInterruptException:
		exit()
	except KeyboardInterrupt:
		exit()