#!/usr/bin/env python

import rospy
import cv2
from std_msgs.msg import String
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError

def main():
    rospy.init_node('cam_test', anonymous=True)
    img_pub = rospy.Publisher('img_topic', Image)
    cam = cv2.VideoCapture(0)
    bridge = CvBridge()
    rate = rospy.Rate(5)

    while not rospy.is_shutdown():
        ret, frame = cam.read()
        #cv2.imshow('frame', frame)

        img_pub.publish(bridge.cv2_to_imgmsg(frame, "bgr8"))

        #if cv2.waitKey(1) & 0xFF == ord('q'):
        #    break
        rate.sleep()    

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        cam.release()

